DROP TABLE cprm.cprm_aflor_geo cascade;

CREATE TABLE cprm.cprm_aflor_geo(
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	geom public.geometry(point, 4674) NULL,
	id_aflor int4 NULL,
	origem varchar NULL,
	mtd_geoposi varchar NULL,
	toponimia varchar NULL,
	mun varchar NULL,
	uf varchar NULL,
	geologo varchar NULL,
	data_cad date NULL,
	tp_aflor varchar NULL,
	descricao varchar NULL,
	n_campo varchar NULL,
	rochas varchar NULL,
	sureg varchar NULL,
	projeto varchar NULL,
	cod_folha varchar NULL,
	folha varchar NULL,
	CONSTRAINT cprm_afloramentos_geologicos_pkey2 PRIMARY KEY (id)
);
CREATE INDEX cprm_aflor_geo_idx2 ON cprm.cprm_aflor_geo_a USING gist (geom);
CREATE INDEX idx_cprm_cprm_aflor_geo2 ON cprm.cprm_aflor_geo_a USING gist (geom);
CREATE INDEX idx_cprm_cprm_aflor_geo_a ON cprm.cprm_aflor_geo_a USING gist (geom);


---------

CREATE OR REPLACE VIEW geoserver.vw_cprm_aflor_geo
AS SELECT cprm_aflor_geo.id,
    cprm_aflor_geo.geom,
    cprm_aflor_geo.id_aflor,
    cprm_aflor_geo.origem,
    cprm_aflor_geo.mtd_geoposi,
    cprm_aflor_geo.toponimia,
    cprm_aflor_geo.mun,
    cprm_aflor_geo.uf,
    cprm_aflor_geo.geologo,
    cprm_aflor_geo.data_cad,
    cprm_aflor_geo.tp_aflor,
    cprm_aflor_geo.descricao,
    cprm_aflor_geo.n_campo,
    cprm_aflor_geo.rochas,
    cprm_aflor_geo.sureg,
    cprm_aflor_geo.projeto,
    cprm_aflor_geo.cod_folha,
    cprm_aflor_geo.folha
   FROM cprm.cprm_aflor_geo;



--------

drop table if exists cprm.cprm_ocorr_min cascade;

CREATE TABLE cprm.cprm_ocorr_min (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(Point, 4674) NULL,
	fid int4 NULL,
	id_aflor int4 NULL,
	origem varchar NULL,
	mtd_geoposi varchar NULL,
	toponimia varchar NULL,
	mun varchar NULL,
	uf varchar NULL,
	geologo varchar NULL,
	data_cad date NULL,
	tp_aflor varchar NULL,
	descricao varchar NULL,
	n_campo varchar NULL,
	rochas varchar NULL,
	sureg varchar NULL,
	projeto varchar NULL,
	cod_folha varchar NULL,
	folha varchar NULL,
	id_ocorr int4 NULL,
	provincia varchar NULL,
	status_econ varchar NULL,
	importancia varchar NULL,
	local_mina varchar NULL,
	situ_mina varchar NULL,
	motivo_inativ_mina varchar NULL,
	situ_garimpo varchar NULL,
	motivo_inativ_garim varchar NULL,
	substancias varchar NULL,
	rochas_hosp varchar NULL,
	rochas_encaix varchar NULL,
	classes_utilitarias varchar NULL,
	morfologia varchar NULL,
	textura varchar NULL,
	tp_alteracao varchar NULL,
	objectid int4 NULL
);

CREATE INDEX cprm_ocorr_min_idx ON cprm.cprm_ocorr_min USING gist (geom);
CREATE INDEX idx_cprm_cprm_ocorr_min ON cprm.cprm_ocorr_min USING btree (id);


-------

-- geoserver.vw_cprm_ocorr_min source

CREATE OR REPLACE VIEW geoserver.vw_cprm_ocorr_min
AS SELECT 
    cprm_ocorr_min.geom,
    cprm_ocorr_min.fid,
    cprm_ocorr_min.id_aflor,
    cprm_ocorr_min.origem,
    cprm_ocorr_min.mtd_geoposi,
    cprm_ocorr_min.toponimia,
    cprm_ocorr_min.mun,
    cprm_ocorr_min.uf,
    cprm_ocorr_min.geologo,
    cprm_ocorr_min.data_cadastro,
    cprm_ocorr_min.tp_aflor,
    cprm_ocorr_min.descricao,
    cprm_ocorr_min.n_campo,
    cprm_ocorr_min.rochas,
    cprm_ocorr_min.sureg,
    cprm_ocorr_min.projeto,
    cprm_ocorr_min.cod_folha,
    cprm_ocorr_min.folha,
    cprm_ocorr_min.id_ocorr,
    cprm_ocorr_min.provincia,
    cprm_ocorr_min.status_econ,
    cprm_ocorr_min.importancia,
    cprm_ocorr_min.local_mina,
    cprm_ocorr_min.situ_mina,
    cprm_ocorr_min.motivo_inativ_mina,
    cprm_ocorr_min.situ_garimpo,
    cprm_ocorr_min.motivo_inativ_garim,
    cprm_ocorr_min.substancias,
    cprm_ocorr_min.rochas_hosp,
    cprm_ocorr_min.rochas_encaix,
    cprm_ocorr_min.classes_utilitarias,
    cprm_ocorr_min.morfologia,
    cprm_ocorr_min.textura,
    cprm_ocorr_min.tp_alteracao,
    cprm_ocorr_min.id as objectid,
   FROM cprm.cprm_ocorr_min;

   ----


   DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN 
        SELECT matviewname 
        FROM pg_matviews 
        WHERE schemaname = 'geoserver'
    LOOP
        EXECUTE format('REFRESH MATERIALIZED VIEW geoserver.%I WITH NO DATA;', r.matviewname);
    END LOOP;
END $$;