--
--
-- -> Arquivo de hotfix para a estrutura de tabelas do Geoserver
-- -> Autor: Victor Arantes
-- -> Data: 2026-07-03
-- -> Descrição: Este arquivo contém alterações na estrutura do banco de dados do Geoserver, 
--recriando as tabelas, views e índices GeoCron + Litoestratigrafia, criando as tables com o parâmetro "GENERATED BY DEFAULT" na pkey (if).
-- -> Este arquivo corrige o bug onde o airflow não consegue realizar a inserção dos dados por constraint de chave primária nula (?).
-- -> OBSERVAÇÃO 1: É melhor executar este patch tendo certeza de que as fontes estão online, pois se não a camada ficará sem dados até
--que o airflow consiga consumir a fonte.
-- -> OBSERVAÇÃO 2: Observou-se que a versão do GDAL (3.2.2 - 03/2021) utilizada na imagem do airflow não faz os 'handlings' para
--os inserts. A versão testada localmente (3.7.2 - 09/2023) já possui essa feature, não sendo necessário este hotfix.
--
--

---------------------DROPS
drop table if exists cprm.cprm_geocron cascade ;
DROP TABLE if exists cprm.cprm_lev_litostrat_100000 cascade;
drop table if exists cprm.cprm_lev_litostrat_25000 cascade ;
DROP TABLE if exists cprm.cprm_lev_litostrat_50000 cascade;
DROP TABLE if exists cprm.cprm_lev_litostrat_250000 cascade;
--------------------------


---------------------CREATES

CREATE TABLE cprm.cprm_geocron (
    id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geom public.geometry(point, 4674) NULL,
    amostra varchar NULL,
    toponomia varchar NULL,
    rocha varchar NULL,
    mtd_geoposi varchar NULL,
    erro_localc varchar NULL,
    mtds varchar NULL,
    mat_analisados varchar NULL,
    nivel_acesso varchar NULL

);
CREATE INDEX cprm_geocron_idx ON cprm.cprm_geocron USING gist (geom);
CREATE INDEX idx_cprm_cprm_geocron ON cprm.cprm_geocron USING btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_25000 (
	id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	hierarquia varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	"range" varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_25000_idx ON cprm.cprm_lev_litostrat_25000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_25000 ON cprm.cprm_lev_litostrat_25000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_50000 (
	id int2 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	hierarquia varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	"range" varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_50000_idx ON cprm.cprm_lev_litostrat_50000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_50000 ON cprm.cprm_lev_litostrat_50000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_100000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar(180) NULL,
	hierarquia varchar(180) NULL,
	nome varchar(254) NULL,
	amb_tecto varchar(180) NULL,
	sub_amb_tectonico varchar(180) NULL,
	sigla_pai varchar(180) NULL,
	nome_pai varchar(254) NULL,
	legenda varchar(254) NULL,
	escala varchar(14) NULL,
	mapa varchar(254) NULL,
	litotipos varchar(254) NULL,
	"range" varchar(50) NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar(180) NULL,
	eon_max varchar(180) NULL,
	era_min varchar(180) NULL,
	era_max varchar(180) NULL,
	sistema_min varchar(180) NULL,
	sistema_ma varchar(180) NULL,
	epoca_min varchar(180) NULL,
	epoca_max varchar(180) NULL,
	siglas_historicas varchar(254) NULL
	
);
CREATE INDEX cprm_lev_litostrat_geom_gist ON cprm.cprm_lev_litostrat_100000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_100000 ON cprm.cprm_lev_litostrat_100000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_250000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	fid int2 NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL,
	shp_area numeric(13, 10) NULL,
	shp_length numeric(13, 10) NULL,
	objectid int8 NULL,
	hierarquia varchar NULL,
	"range" varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_250000_idx ON cprm.cprm_lev_litostrat_250000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_250000 ON cprm.cprm_lev_litostrat_250000 USING btree (id);

---------------------------VIEWS 

CREATE OR REPLACE VIEW geoserver.vw_cprm_geocron
AS SELECT cprm_geocron.id,
    cprm_geocron.geom,
    cprm_geocron.amostra,
    cprm_geocron.toponomia,
    cprm_geocron.rocha,
    cprm_geocron.mtd_geoposi,
    cprm_geocron.erro_localc,
    cprm_geocron.mtds,
    cprm_geocron.mat_analisados,
    cprm_geocron.nivel_acesso
   FROM cprm.cprm_geocron;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_25000
AS SELECT cprm_lev_litostrat_25000.id,
    cprm_lev_litostrat_25000.geom,
    cprm_lev_litostrat_25000.id_uni_estratigrafica,
    cprm_lev_litostrat_25000.sigla,
    cprm_lev_litostrat_25000.hierarquia,
    cprm_lev_litostrat_25000.nome,
    cprm_lev_litostrat_25000.amb_tecto,
    cprm_lev_litostrat_25000.sub_amb_tectonico,
    cprm_lev_litostrat_25000.sigla_pai,
    cprm_lev_litostrat_25000.nome_pai,
    cprm_lev_litostrat_25000.legenda,
    cprm_lev_litostrat_25000.escala,
    cprm_lev_litostrat_25000.mapa,
    cprm_lev_litostrat_25000.litotipos,
    cprm_lev_litostrat_25000.range,
    cprm_lev_litostrat_25000.idade_min,
    cprm_lev_litostrat_25000.idade_max,
    cprm_lev_litostrat_25000.eon_min,
    cprm_lev_litostrat_25000.eon_max,
    cprm_lev_litostrat_25000.era_min,
    cprm_lev_litostrat_25000.era_max,
    cprm_lev_litostrat_25000.sistema_min,
    cprm_lev_litostrat_25000.sistema_max,
    cprm_lev_litostrat_25000.epoca_min,
    cprm_lev_litostrat_25000.epoca_max,
    cprm_lev_litostrat_25000.siglas_historicas,
    cprm_lev_litostrat_25000.grupo
   FROM cprm.cprm_lev_litostrat_25000;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_50000
AS SELECT cprm_lev_litostrat_50000.id,
    cprm_lev_litostrat_50000.geom,
    cprm_lev_litostrat_50000.id_uni_estratigrafica,
    cprm_lev_litostrat_50000.sigla,
    cprm_lev_litostrat_50000.hierarquia,
    cprm_lev_litostrat_50000.nome,
    cprm_lev_litostrat_50000.amb_tecto,
    cprm_lev_litostrat_50000.sub_amb_tectonico,
    cprm_lev_litostrat_50000.sigla_pai,
    cprm_lev_litostrat_50000.nome_pai,
    cprm_lev_litostrat_50000.legenda,
    cprm_lev_litostrat_50000.escala,
    cprm_lev_litostrat_50000.mapa,
    cprm_lev_litostrat_50000.litotipos,
    cprm_lev_litostrat_50000.range,
    cprm_lev_litostrat_50000.idade_min,
    cprm_lev_litostrat_50000.idade_max,
    cprm_lev_litostrat_50000.eon_min,
    cprm_lev_litostrat_50000.eon_max,
    cprm_lev_litostrat_50000.era_min,
    cprm_lev_litostrat_50000.era_max,
    cprm_lev_litostrat_50000.sistema_min,
    cprm_lev_litostrat_50000.sistema_max,
    cprm_lev_litostrat_50000.epoca_min,
    cprm_lev_litostrat_50000.epoca_max,
    cprm_lev_litostrat_50000.siglas_historicas,
    cprm_lev_litostrat_50000.grupo
   FROM cprm.cprm_lev_litostrat_50000;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_100000
AS SELECT cprm_lev_litostrat_100000.id,
    cprm_lev_litostrat_100000.geom,
    cprm_lev_litostrat_100000.id_uni_estratigrafica,
    cprm_lev_litostrat_100000.sigla,
    cprm_lev_litostrat_100000.hierarquia,
    cprm_lev_litostrat_100000.nome,
    cprm_lev_litostrat_100000.amb_tecto,
    cprm_lev_litostrat_100000.sub_amb_tectonico,
    cprm_lev_litostrat_100000.sigla_pai,
    cprm_lev_litostrat_100000.nome_pai,
    cprm_lev_litostrat_100000.legenda,
    cprm_lev_litostrat_100000.escala,
    cprm_lev_litostrat_100000.mapa,
    cprm_lev_litostrat_100000.litotipos,
    cprm_lev_litostrat_100000.range,
    cprm_lev_litostrat_100000.idade_min,
    cprm_lev_litostrat_100000.idade_max,
    cprm_lev_litostrat_100000.eon_min,
    cprm_lev_litostrat_100000.eon_max,
    cprm_lev_litostrat_100000.era_min,
    cprm_lev_litostrat_100000.era_max,
    cprm_lev_litostrat_100000.sistema_min,
    cprm_lev_litostrat_100000.sistema_ma,
    cprm_lev_litostrat_100000.epoca_min,
    cprm_lev_litostrat_100000.epoca_max,
    cprm_lev_litostrat_100000.siglas_historicas
   FROM cprm.cprm_lev_litostrat_100000;

   --

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_250000
AS SELECT cprm_lev_litostrat_250000.id,
    cprm_lev_litostrat_250000.geom,
    cprm_lev_litostrat_250000.fid,
    cprm_lev_litostrat_250000.id_uni_estratigrafica,
    cprm_lev_litostrat_250000.sigla,
    cprm_lev_litostrat_250000.nome,
    cprm_lev_litostrat_250000.amb_tecto,
    cprm_lev_litostrat_250000.sub_amb_tectonico,
    cprm_lev_litostrat_250000.sigla_pai,
    cprm_lev_litostrat_250000.nome_pai,
    cprm_lev_litostrat_250000.legenda,
    cprm_lev_litostrat_250000.escala,
    cprm_lev_litostrat_250000.mapa,
    cprm_lev_litostrat_250000.litotipos,
    cprm_lev_litostrat_250000.idade_min,
    cprm_lev_litostrat_250000.idade_max,
    cprm_lev_litostrat_250000.eon_min,
    cprm_lev_litostrat_250000.eon_max,
    cprm_lev_litostrat_250000.era_min,
    cprm_lev_litostrat_250000.era_max,
    cprm_lev_litostrat_250000.sistema_min,
    cprm_lev_litostrat_250000.sistema_max,
    cprm_lev_litostrat_250000.epoca_min,
    cprm_lev_litostrat_250000.epoca_max,
    cprm_lev_litostrat_250000.siglas_historicas,
    cprm_lev_litostrat_250000.grupo,
    cprm_lev_litostrat_250000.shp_area,
    cprm_lev_litostrat_250000.shp_length,
    cprm_lev_litostrat_250000.objectid,
    cprm_lev_litostrat_250000.hierarquia,
    cprm_lev_litostrat_250000.range
   FROM cprm.cprm_lev_litostrat_250000;

   ----------------------------------------------------