--
--
-- -> Arquivo de hotfix para a estrutura de tabelas do Geoserver
-- -> Autor: Victor Arantes
-- -> Data: 2026-07-03
-- -> Descrição: Este arquivo contém alterações na estrutura do banco de dados do Geoserver, 
--recriando as tabelas, views e índices GeoCron + Litoestratigrafia, criando as tables com o parâmetro "GENERATED BY DEFAULT" na pkey (if).
-- -> Este arquivo corrige o bug onde o airflow não consegue realizar a inserção dos dados por constraint de chave primária nula (?).
-- -> OBSERVAÇÃO 1: É melhor executar este patch tendo certeza de que as fontes estão online, pois se não a camada ficará sem dados até
--que o airflow consiga consumir a fonte.
-- -> OBSERVAÇÃO 2: Observou-se que a versão do GDAL (3.2.2 - 03/2021) utilizada na imagem do airflow não faz os 'handlings' para
--os inserts. A versão testada localmente (3.7.2 - 09/2023) já possui essa feature, não sendo necessário este hotfix.
--
-- fix1: Campos id alterados para int4 para comportar valores de id do geoportal- 17/07/2026

---------------------------v2 - 30/07/2026

-- Adicionadas novas camadas: Furos de Sondagem (cprm_furos_sondagem), Litoestratigrafia 1:2.500.000 (cprm_lev_litostrat_2500000), Modelamento 3d (cprm_modelamento_3d), Cartas de Anomalia (cprm_cartas_anomalia)
-- Rodar airflow 1x para consumir fonte e criar tabelas e script para criar indices e mviews


---------------------------v3 - 21/08/2026

-- hot fix para estrutura/modelagem processos minerarios ativos agrupados (mvw_pma_agrupado)



---------------------DROPS
drop table if exists cprm.cprm_geocron cascade ;
DROP TABLE if exists cprm.cprm_lev_litostrat_100000 cascade;
drop table if exists cprm.cprm_lev_litostrat_25000 cascade ;
DROP TABLE if exists cprm.cprm_lev_litostrat_50000 cascade;
DROP TABLE if exists cprm.cprm_lev_litostrat_250000 cascade;
--------------------------


---------------------CREATES

CREATE TABLE cprm.cprm_geocron (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geom public.geometry(point, 4674) NULL,
    amostra varchar NULL,
    toponimia varchar NULL,
    rocha varchar NULL,
    mtd_geoposi varchar NULL,
    erro_localc varchar NULL,
    mtds varchar NULL,
    mat_analisados varchar NULL,
    nivel_acesso varchar NULL

);
CREATE INDEX cprm_geocron_idx ON cprm.cprm_geocron USING gist (geom);
CREATE INDEX idx_cprm_cprm_geocron ON cprm.cprm_geocron USING btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_25000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	hierarquia varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	"range" varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_25000_idx ON cprm.cprm_lev_litostrat_25000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_25000 ON cprm.cprm_lev_litostrat_25000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_50000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	hierarquia varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	"range" varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_50000_idx ON cprm.cprm_lev_litostrat_50000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_50000 ON cprm.cprm_lev_litostrat_50000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_100000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar(180) NULL,
	hierarquia varchar(180) NULL,
	nome varchar(254) NULL,
	amb_tecto varchar(180) NULL,
	sub_amb_tectonico varchar(180) NULL,
	sigla_pai varchar(180) NULL,
	nome_pai varchar(254) NULL,
	legenda varchar(254) NULL,
	escala varchar(14) NULL,
	mapa varchar(254) NULL,
	litotipos varchar(254) NULL,
	"range" varchar(50) NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar(180) NULL,
	eon_max varchar(180) NULL,
	era_min varchar(180) NULL,
	era_max varchar(180) NULL,
	sistema_min varchar(180) NULL,
	sistema_ma varchar(180) NULL,
	epoca_min varchar(180) NULL,
	epoca_max varchar(180) NULL,
	siglas_historicas varchar(254) NULL
	
);
CREATE INDEX cprm_lev_litostrat_geom_gist ON cprm.cprm_lev_litostrat_100000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_100000 ON cprm.cprm_lev_litostrat_100000 using btree (id);

--

CREATE TABLE cprm.cprm_lev_litostrat_250000 (
	id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	geom public.geometry(multipolygon, 4674) NULL,
	fid int2 NULL,
	id_uni_estratigrafica int2 NULL,
	sigla varchar NULL,
	nome varchar NULL,
	amb_tecto varchar NULL,
	sub_amb_tectonico varchar NULL,
	sigla_pai varchar NULL,
	nome_pai varchar NULL,
	legenda varchar NULL,
	escala varchar NULL,
	mapa varchar NULL,
	litotipos varchar NULL,
	idade_min int2 NULL,
	idade_max int2 NULL,
	eon_min varchar NULL,
	eon_max varchar NULL,
	era_min varchar NULL,
	era_max varchar NULL,
	sistema_min varchar NULL,
	sistema_max varchar NULL,
	epoca_min varchar NULL,
	epoca_max varchar NULL,
	siglas_historicas varchar NULL,
	grupo varchar NULL,
	shp_area numeric(13, 10) NULL,
	shp_length numeric(13, 10) NULL,
	objectid int8 NULL,
	hierarquia varchar NULL,
	"range" varchar NULL
	
);
CREATE INDEX cprm_lev_litostrat_250000_idx ON cprm.cprm_lev_litostrat_250000 USING gist (geom);
CREATE INDEX idx_cprm_cprm_lev_litostrat_250000 ON cprm.cprm_lev_litostrat_250000 USING btree (id);

---------------------------VIEWS 

CREATE OR REPLACE VIEW geoserver.vw_cprm_geocron
AS SELECT cprm_geocron.id,
    cprm_geocron.geom,
    cprm_geocron.amostra,
    cprm_geocron.toponomia,
    cprm_geocron.rocha,
    cprm_geocron.mtd_geoposi,
    cprm_geocron.erro_localc,
    cprm_geocron.mtds,
    cprm_geocron.mat_analisados,
    cprm_geocron.nivel_acesso
   FROM cprm.cprm_geocron;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_25000
AS SELECT cprm_lev_litostrat_25000.id,
    cprm_lev_litostrat_25000.geom,
    cprm_lev_litostrat_25000.id_uni_estratigrafica,
    cprm_lev_litostrat_25000.sigla,
    cprm_lev_litostrat_25000.hierarquia,
    cprm_lev_litostrat_25000.nome,
    cprm_lev_litostrat_25000.amb_tecto,
    cprm_lev_litostrat_25000.sub_amb_tectonico,
    cprm_lev_litostrat_25000.sigla_pai,
    cprm_lev_litostrat_25000.nome_pai,
    cprm_lev_litostrat_25000.legenda,
    cprm_lev_litostrat_25000.escala,
    cprm_lev_litostrat_25000.mapa,
    cprm_lev_litostrat_25000.litotipos,
    cprm_lev_litostrat_25000.range,
    cprm_lev_litostrat_25000.idade_min,
    cprm_lev_litostrat_25000.idade_max,
    cprm_lev_litostrat_25000.eon_min,
    cprm_lev_litostrat_25000.eon_max,
    cprm_lev_litostrat_25000.era_min,
    cprm_lev_litostrat_25000.era_max,
    cprm_lev_litostrat_25000.sistema_min,
    cprm_lev_litostrat_25000.sistema_max,
    cprm_lev_litostrat_25000.epoca_min,
    cprm_lev_litostrat_25000.epoca_max,
    cprm_lev_litostrat_25000.siglas_historicas,
    cprm_lev_litostrat_25000.grupo
   FROM cprm.cprm_lev_litostrat_25000;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_50000
AS SELECT cprm_lev_litostrat_50000.id,
    cprm_lev_litostrat_50000.geom,
    cprm_lev_litostrat_50000.id_uni_estratigrafica,
    cprm_lev_litostrat_50000.sigla,
    cprm_lev_litostrat_50000.hierarquia,
    cprm_lev_litostrat_50000.nome,
    cprm_lev_litostrat_50000.amb_tecto,
    cprm_lev_litostrat_50000.sub_amb_tectonico,
    cprm_lev_litostrat_50000.sigla_pai,
    cprm_lev_litostrat_50000.nome_pai,
    cprm_lev_litostrat_50000.legenda,
    cprm_lev_litostrat_50000.escala,
    cprm_lev_litostrat_50000.mapa,
    cprm_lev_litostrat_50000.litotipos,
    cprm_lev_litostrat_50000.range,
    cprm_lev_litostrat_50000.idade_min,
    cprm_lev_litostrat_50000.idade_max,
    cprm_lev_litostrat_50000.eon_min,
    cprm_lev_litostrat_50000.eon_max,
    cprm_lev_litostrat_50000.era_min,
    cprm_lev_litostrat_50000.era_max,
    cprm_lev_litostrat_50000.sistema_min,
    cprm_lev_litostrat_50000.sistema_max,
    cprm_lev_litostrat_50000.epoca_min,
    cprm_lev_litostrat_50000.epoca_max,
    cprm_lev_litostrat_50000.siglas_historicas,
    cprm_lev_litostrat_50000.grupo
   FROM cprm.cprm_lev_litostrat_50000;

--

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_100000
AS SELECT cprm_lev_litostrat_100000.id,
    cprm_lev_litostrat_100000.geom,
    cprm_lev_litostrat_100000.id_uni_estratigrafica,
    cprm_lev_litostrat_100000.sigla,
    cprm_lev_litostrat_100000.hierarquia,
    cprm_lev_litostrat_100000.nome,
    cprm_lev_litostrat_100000.amb_tecto,
    cprm_lev_litostrat_100000.sub_amb_tectonico,
    cprm_lev_litostrat_100000.sigla_pai,
    cprm_lev_litostrat_100000.nome_pai,
    cprm_lev_litostrat_100000.legenda,
    cprm_lev_litostrat_100000.escala,
    cprm_lev_litostrat_100000.mapa,
    cprm_lev_litostrat_100000.litotipos,
    cprm_lev_litostrat_100000.range,
    cprm_lev_litostrat_100000.idade_min,
    cprm_lev_litostrat_100000.idade_max,
    cprm_lev_litostrat_100000.eon_min,
    cprm_lev_litostrat_100000.eon_max,
    cprm_lev_litostrat_100000.era_min,
    cprm_lev_litostrat_100000.era_max,
    cprm_lev_litostrat_100000.sistema_min,
    cprm_lev_litostrat_100000.sistema_ma,
    cprm_lev_litostrat_100000.epoca_min,
    cprm_lev_litostrat_100000.epoca_max,
    cprm_lev_litostrat_100000.siglas_historicas
   FROM cprm.cprm_lev_litostrat_100000;

   --

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_250000
AS SELECT cprm_lev_litostrat_250000.id,
    cprm_lev_litostrat_250000.geom,
    cprm_lev_litostrat_250000.fid,
    cprm_lev_litostrat_250000.id_uni_estratigrafica,
    cprm_lev_litostrat_250000.sigla,
    cprm_lev_litostrat_250000.nome,
    cprm_lev_litostrat_250000.amb_tecto,
    cprm_lev_litostrat_250000.sub_amb_tectonico,
    cprm_lev_litostrat_250000.sigla_pai,
    cprm_lev_litostrat_250000.nome_pai,
    cprm_lev_litostrat_250000.legenda,
    cprm_lev_litostrat_250000.escala,
    cprm_lev_litostrat_250000.mapa,
    cprm_lev_litostrat_250000.litotipos,
    cprm_lev_litostrat_250000.idade_min,
    cprm_lev_litostrat_250000.idade_max,
    cprm_lev_litostrat_250000.eon_min,
    cprm_lev_litostrat_250000.eon_max,
    cprm_lev_litostrat_250000.era_min,
    cprm_lev_litostrat_250000.era_max,
    cprm_lev_litostrat_250000.sistema_min,
    cprm_lev_litostrat_250000.sistema_max,
    cprm_lev_litostrat_250000.epoca_min,
    cprm_lev_litostrat_250000.epoca_max,
    cprm_lev_litostrat_250000.siglas_historicas,
    cprm_lev_litostrat_250000.grupo,
    cprm_lev_litostrat_250000.shp_area,
    cprm_lev_litostrat_250000.shp_length,
    cprm_lev_litostrat_250000.objectid,
    cprm_lev_litostrat_250000.hierarquia,
    cprm_lev_litostrat_250000.range
   FROM cprm.cprm_lev_litostrat_250000;

   ----------------------------------------------------
--------------------------------------------------------------- V2 - Novas camadas -> rodar airflow 1x para consumir fonte e criar tabelas
---
--index Furos de Sondagem

CREATE INDEX cprm_furos_sondagem_idx ON cprm.cprm_furos_sondagem USING gist (geom);
CREATE INDEX idx_cprm_furos_sondagem ON cprm.cprm_furos_sondagem USING btree (ogc_fid);

--mview Furos de Sondagem

create or replace view geoserver.cprm_furos_sondagem as select * from (

WITH collar_summary AS (
    SELECT 
        bhid,
        COUNT(*) AS contagem_de_intervalos,
        STRING_AGG(concat(from_, '-', to_), ', ' ORDER BY from_ ASC) AS intervalos_furo,
        STRING_AGG(DISTINCT unidade_maior, ', ') AS unidades_maiores,
        STRING_AGG(DISTINCT unidade_estratigrafica, ', ') AS unidades_estratigraficas,
        string_agg(distinct url_rigeo, ',') as url_rigeo,
        string_agg(distinct profile_image, ',')  profile_image
    FROM 
        cprm.cprm_furos_sondagem
    GROUP BY 
        bhid
)
SELECT DISTINCT ON (c.bhid)
    c.bhid,
    c.projeto,
    c.xcollar,
    c.ycollar,
    c.zcollar,
    c.end_depth,
    c.geom, 
    c.area_projeto,
    s.profile_image,
    s.contagem_de_intervalos,
    s.intervalos_furo,
    s.unidades_maiores,
    s.unidades_estratigraficas,
    s.url_rigeo
    
FROM 
    cprm.cprm_furos_sondagem c
JOIN 
    collar_summary s ON c.bhid = s.bhid
ORDER BY 
    c.bhid
) a ;

--

-- Index Litoestratigrafia 1:2.500.000
CREATE INDEX cprm_lev_litostrat_2500000_idx ON cprm.cprm_lev_litostrat_2500000 USING gist (geom);
CREATE INDEX idx_cprm_lev_litostrat_2500000 ON cprm.cprm_lev_litostrat_2500000 USING btree (id);

-- View Litoestratigrafia 1:2.500.000

CREATE OR REPLACE VIEW geoserver.vw_cprm_lev_litostrat_2500000
AS SELECT * from cprm.cprm_lev_litostrat_2500000;

--

-- Index Modelamento 3D
CREATE INDEX cprm_modelamento_3d_idx ON cprm.cprm_modelamento_3d USING gist (geom);
CREATE INDEX idx_cprm_modelamento_3d ON cprm.cprm_modelamento_3d USING btree (ogc_fid);

-- View Modelamento 3D
CREATE OR REPLACE VIEW geoserver.vw_cprm_modelamento_3d
AS SELECT * FROM cprm.cprm_modelamento_3d;

--

CREATE INDEX cprm_cartas_anomalia_idx ON cprm.cprm_cartas_anomalia USING gist (geom);
CREATE INDEX idx_cprm_cartas_anomalia ON cprm.cprm_cartas_anomalia USING btree (ogc_fid);

-- View Cartas de Anomalia
CREATE OR REPLACE VIEW geoserver.vw_cprm_cartas_anomalia
AS SELECT * FROM cprm.cprm_cartas_anomalia;


------------------------------------------------------------------ HOT FIX PMA AGRUPADO --------------------- 21/08/26 -V3

drop materialized view geoserver.mvw_minas_ativas_grp;
DROP MATERIALIZED VIEW geoserver.mvw_grupos_minerarios;
drop materialized view geoserver.mvw_pma_agrupado;

----------- PMA AGRUPADO NOVO: DEPENDE DA NOVA TABLE anm.tb_processoassociacao -> atualizada pelo airflow // contagem de 2530 -> 2565

CREATE MATERIALIZED VIEW geoserver.mvw_pma_agrupado
TABLESPACE pg_default
AS SELECT DISTINCT mpma.id,
    mpma.geom,
    mpma.ds_processo,
    mpma.qt_area,
    mpma.nm_pessoa,
    mpma.nm_substancia,
    mpma.tipo_uso,
    mpma.nm_mun,
    mpma.cod_mun,
    mpma.sigla_uf,
    mpma.regiao_estado,
    mpma.substancia_agrupadora_id,
    mpma.ds_fase_processo,
    mpma.ds_fase_agrupada,
    ac_assoc.processo_minerario AS processo_grupo_minerario,
    ac_assoc.dsprocessoassociado AS proc_associado,
    COALESCE(ac_assoc.processo_minerario, mpma.ds_processo::text) AS processo_final
   FROM geoserver.mvw_processos_minerarios_ativos mpma
     LEFT JOIN ( SELECT ac.dsprocessoassociado,
            ac.dsprocesso AS processo_minerario
           FROM anm.tb_processoassociacao ac
          WHERE ac.idtipoassociacao = 4) ac_assoc ON mpma.ds_processo::text = ac_assoc.dsprocessoassociado
WITH DATA;

------- MINAS ATIVAS


CREATE MATERIALIZED VIEW geoserver.mvw_minas_ativas_grp
TABLESPACE pg_default
AS SELECT mpma.id,
    mpma.geom,
    mpma.ds_processo,
    mpma.processo_final AS ds_processo_grp_min,
    mpma.qt_area,
    mpma.nm_pessoa,
    mpma.nm_mun,
    mpma.cod_mun,
    mpma.sigla_uf,
    mpma.regiao_estado,
    mpma.tipo_uso,
    caa.substancia AS nm_substancia,
    psm.substanciaagrupadora_id::character varying(5) AS substancia_agrupadora_id,
    mpma.ds_fase_processo,
    mpma.ds_fase_agrupada,
    sum(caa.vl_recolhido) AS total_recolhido,
    sum(caa.qt_comercializada) AS total_produzido
   FROM anm.cfem_arrecadacao_ativa caa
     JOIN geoserver.mvw_pma_agrupado mpma ON replace(mpma.processo_final, '.'::text, ''::text) = caa.processo_ano
     JOIN p3m_substanciamineral psm ON psm.nome::text = caa.substancia
  WHERE caa.data_recolhimento_cfem >= (CURRENT_DATE - '1 year'::interval)
  GROUP BY mpma.id, mpma.geom, mpma.ds_processo, mpma.processo_final, mpma.qt_area, mpma.nm_pessoa, mpma.tipo_uso, mpma.nm_mun, mpma.cod_mun, mpma.sigla_uf, mpma.regiao_estado, caa.substancia, psm.substanciaagrupadora_id, mpma.ds_fase_processo, mpma.ds_fase_agrupada
WITH DATA;

-- View indexes:
CREATE INDEX mma_ds_idx_grp ON geoserver.mvw_minas_ativas_grp USING btree (ds_processo);
CREATE INDEX mma_geom_idx_grp ON geoserver.mvw_minas_ativas_grp USING gist (geom);
CREATE INDEX mma_id_agrp_idx_grp ON geoserver.mvw_minas_ativas_grp USING btree (substancia_agrupadora_id);


------- GRUPOS MINERARIOS

CREATE MATERIALIZED VIEW geoserver.mvw_grupos_minerarios
TABLESPACE pg_default
AS SELECT DISTINCT row_number() OVER () AS id,
    st_multi(mpma.geom)::geometry(MultiPolygon,4674) AS geom,
    mpma.processo_final AS ds_processo,
    mpma.qt_area,
    mpma.nm_pessoa,
    mpma.nm_mun,
    mpma.cod_mun,
    mpma.sigla_uf,
    mpma.regiao_estado,
    mpma.tipo_uso,
    caa.substancia::character varying(50) AS nm_substancia,
    psm.substanciaagrupadora_id::character varying(5) AS substancia_agrupadora_id,
    mpma.ds_fase_processo,
    mpma.ds_fase_agrupada,
    sum(caa.vl_recolhido) AS total_recolhido,
    sum(caa.qt_comercializada) AS total_produzido
   FROM anm.cfem_arrecadacao_ativa caa
     JOIN ( SELECT mvw_pma_agrupado.id,
            mvw_pma_agrupado.geom,
            mvw_pma_agrupado.ds_processo,
            mvw_pma_agrupado.qt_area,
            mvw_pma_agrupado.nm_pessoa,
            mvw_pma_agrupado.nm_substancia,
            mvw_pma_agrupado.tipo_uso,
            mvw_pma_agrupado.nm_mun,
            mvw_pma_agrupado.cod_mun,
            mvw_pma_agrupado.sigla_uf,
            mvw_pma_agrupado.regiao_estado,
            mvw_pma_agrupado.substancia_agrupadora_id,
            mvw_pma_agrupado.ds_fase_processo,
            mvw_pma_agrupado.ds_fase_agrupada,
            mvw_pma_agrupado.processo_grupo_minerario,
            mvw_pma_agrupado.proc_associado,
            mvw_pma_agrupado.processo_final
           FROM geoserver.mvw_pma_agrupado
          WHERE mvw_pma_agrupado.processo_grupo_minerario IS NOT NULL) mpma ON replace(mpma.processo_final, '.'::text, ''::text) = caa.processo_ano
     JOIN p3m_substanciamineral psm ON psm.nome::text = caa.substancia
  WHERE caa.data_recolhimento_cfem >= (CURRENT_DATE - '1 year'::interval)
  GROUP BY mpma.id, mpma.geom, mpma.processo_final, mpma.qt_area, mpma.nm_pessoa, mpma.tipo_uso, mpma.nm_mun, mpma.cod_mun, mpma.sigla_uf, mpma.regiao_estado, caa.substancia, psm.substanciaagrupadora_id, mpma.ds_fase_processo, mpma.ds_fase_agrupada
WITH DATA;

-- View indexes:
CREATE INDEX mma_ds_gp_mn1 ON geoserver.mvw_grupos_minerarios USING btree (ds_processo);
CREATE INDEX mma_geom_idx_gp_mn1 ON geoserver.mvw_grupos_minerarios USING gist (geom);
CREATE INDEX mma_id_agrp_idx_gp_mn1 ON geoserver.mvw_grupos_minerarios USING btree (substancia_agrupadora_id);


--- DDL ANTIGA PMA AGRUPADO ----------> NÃO RODAR


-- geoserver.mvw_pma_agrupado source

CREATE MATERIALIZED VIEW geoserver.mvw_pma_agrupado
TABLESPACE pg_default
AS SELECT DISTINCT mpma.id,
    mpma.geom,
    mpma.ds_processo,
    mpma.qt_area,
    mpma.nm_pessoa,
    mpma.nm_substancia,
    mpma.tipo_uso,
    mpma.nm_mun,
    mpma.cod_mun,
    mpma.sigla_uf,
    mpma.regiao_estado,
    mpma.substancia_agrupadora_id,
    mpma.ds_fase_processo,
    mpma.ds_fase_agrupada,
    ac_assoc.processo_minerario AS processo_grupo_minerario,
    ac_assoc.ds_processo_associado AS proc_associado,
    COALESCE(ac_assoc.processo_minerario, mpma.ds_processo::text) AS processo_final
   FROM geoserver.mvw_processos_minerarios_ativos mpma
     LEFT JOIN ( SELECT ac.ds_processo_associado,
            ac.ds_processo AS processo_minerario
           FROM p3m_associacoes ac
          WHERE ac.id_tipo_associacao = 4) ac_assoc ON mpma.ds_processo::text = ac_assoc.ds_processo_associado
WITH DATA;

---------------------------------------